import { Document, Page, View, Text, StyleSheet } from '@react-pdf/renderer'
import type { Purchase } from '@/lib/types'

const styles = StyleSheet.create({
  page: {
    padding: 48,
    fontFamily: 'Helvetica',
    fontSize: 10,
    color: '#1a1a1a',
  },
  title: {
    fontSize: 20,
    fontFamily: 'Helvetica-Bold',
    marginBottom: 24,
    textAlign: 'center',
  },
  section: {
    marginBottom: 16,
  },
  row: {
    flexDirection: 'row',
    marginBottom: 4,
  },
  label: {
    width: 100,
    fontFamily: 'Helvetica-Bold',
    color: '#555',
  },
  value: {
    flex: 1,
  },
  divider: {
    borderBottomWidth: 1,
    borderBottomColor: '#e0e0e0',
    marginVertical: 12,
  },
  tableHeader: {
    flexDirection: 'row',
    backgroundColor: '#f5f5f5',
    padding: '6 8',
    fontFamily: 'Helvetica-Bold',
    borderBottomWidth: 1,
    borderBottomColor: '#ccc',
  },
  tableRow: {
    flexDirection: 'row',
    padding: '5 8',
    borderBottomWidth: 1,
    borderBottomColor: '#ebebeb',
  },
  colName: { flex: 3 },
  colQty: { flex: 1, textAlign: 'center' },
  colPrice: { flex: 2, textAlign: 'right' },
  colSubtotal: { flex: 2, textAlign: 'right' },
  totalRow: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    marginTop: 8,
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: '#555',
  },
  totalLabel: {
    fontFamily: 'Helvetica-Bold',
    marginRight: 16,
  },
  totalValue: {
    fontFamily: 'Helvetica-Bold',
    minWidth: 80,
    textAlign: 'right',
  },
  footer: {
    marginTop: 32,
    color: '#888',
    fontSize: 8,
    textAlign: 'center',
  },
})

function fmtDate(iso: string) {
  return iso.slice(0, 10)
}

function fmtNum(n: number) {
  return n.toLocaleString('en-US')
}

interface Props {
  purchase: Purchase
}

export function PurchaseDocument({ purchase }: Props) {
  const items = purchase.purchase_items ?? []

  return (
    <Document>
      <Page size='A4' style={styles.page}>
        <Text style={styles.title}>Purchase Order</Text>

        <View style={styles.section}>
          <View style={styles.row}>
            <Text style={styles.label}>Order ID</Text>
            <Text style={styles.value}>{purchase.id}</Text>
          </View>
          <View style={styles.row}>
            <Text style={styles.label}>Supplier</Text>
            <Text style={styles.value}>{purchase.supplier?.name ?? '-'}</Text>
          </View>
          <View style={styles.row}>
            <Text style={styles.label}>Date</Text>
            <Text style={styles.value}>{fmtDate(purchase.ordered_at)}</Text>
          </View>
          <View style={styles.row}>
            <Text style={styles.label}>Status</Text>
            <Text style={styles.value}>{purchase.status}</Text>
          </View>
        </View>

        <View style={styles.divider} />

        <View style={styles.section}>
          <View style={styles.tableHeader}>
            <Text style={styles.colName}>Item</Text>
            <Text style={styles.colQty}>Qty</Text>
            <Text style={styles.colPrice}>Unit Price</Text>
            <Text style={styles.colSubtotal}>Subtotal</Text>
          </View>
          {items.map((item, idx) => (
            <View key={idx} style={styles.tableRow}>
              <Text style={styles.colName}>
                {item.product?.name ?? item.product_id}
              </Text>
              <Text style={styles.colQty}>{item.quantity}</Text>
              <Text style={styles.colPrice}>{fmtNum(item.purchase_price)}</Text>
              <Text style={styles.colSubtotal}>
                {fmtNum(item.purchase_price * item.quantity)}
              </Text>
            </View>
          ))}
        </View>

        <View style={styles.totalRow}>
          <Text style={styles.totalLabel}>Total</Text>
          <Text style={styles.totalValue}>{fmtNum(purchase.total_amount)}</Text>
        </View>

        <Text style={styles.footer}>
          Generated by DAITEM · {new Date().toISOString().slice(0, 10)}
        </Text>
      </Page>
    </Document>
  )
}
